/*
 * Project Name: async_sram.cyfx
 * Time : 01/06/2012 12:30:15
 * Device Type: FX3
 * Project Type: GPIF2
 *
 *
 *
 *
 * This is a generated file and should not be modified
 * This file is generated by Gpif2 designer tool version - 0.9.652.0
 * 
 */

#ifndef _INCLUDED_CYFXGPIF2CONFIG_
#define _INCLUDED_CYFXGPIF2CONFIG_
#include "cyu3types.h"
#include "cyu3gpif.h"

/* Summary
   Number of states in the state machine
 */
#define CY_NUMBER_OF_STATES 7

/* Summary
   Mapping of user defined state names to state indices
 */
#define ASYNC_SRAM_RESET 0x0
#define ASYNC_SRAM_IDLE 0x1
#define ASYNC_SRAM_READ 0x2
#define ASYNC_SRAM_WRITE_START 0x3
#define ASYNC_SRAM_ADDR_COMP 0x4
#define ASYNC_SRAM_READ_DONE 0x6
#define ASYNC_SRAM_WRITE 0x5


/* Summary
   Macros for pre alphas
 */
#define ASYNC_SRAM_ALPHA_RESET 0x8


/* Summary
   Transition function values which have to be stored GPIF II transition function registers.
 */
uint16_t Async_Sram_CyFxGpifTransition[]  = {
    0x0000, 0x2020, 0x8888, 0xAAAA, 0x5555, 0x3F3F, 0x7777, 0xCCCC
};

/* Summary
   Table containing the transition information for various states. 
   This table has to be stored in the WAVEFORM Registers.
   This array consists of non-replicated waveform descriptors acts as a 
   waveform table. 
 */
CyU3PGpifWaveData Async_Sram_CyFxGpifWavedata[]  = {
    {{0x1E082001,0x000100C4,0x80000000},{0x00000000,0x00000000,0x00000000}},
    {{0x3E738202,0x10000240,0xC0000000},{0x6E702003,0x00000000,0x80000000}},
    {{0x4E72C204,0x0000C00E,0xC0000000},{0x00000000,0x00000000,0x00000000}},
    {{0x6E702005,0x20000200,0xC0000000},{0x00000000,0x00000000,0x00000000}},
    {{0x3E040206,0x000200CA,0x80000000},{0x3E738202,0x10000240,0xC0000000}},
    {{0x3E738202,0x10000240,0xC0000000},{0x1E082001,0x000100C4,0x80000000}}
};

/* Summary
   Table that maps state indices to the descriptor table indices.
 */
uint8_t Async_Sram_CyFxGpifWavedataPosition[]  = {
    0,1,2,3,4,0,5
};

/* Summary
   GPIF II configuration register values.
 */
uint32_t Async_Sram_CyFxGpifRegValue[]  = {
    0xC0000A12,  /*  PIB_GPIF_CONFIG */
    0x00001D67,  /*  PIB_GPIF_BUS_CONFIG */
    0x00000000,  /*  PIB_GPIF_BUS_CONFIG2 */
    0x00000044,  /*  PIB_GPIF_AD_CONFIG */
    0x00000000,  /*  PIB_GPIF_STATUS */
    0x00000000,  /*  PIB_GPIF_INTR */
    0x00000000,  /*  PIB_GPIF_INTR_MASK */
    0x00000082,  /*  PIB_GPIF_SERIAL_IN_CONFIG */
    0x00000782,  /*  PIB_GPIF_SERIAL_OUT_CONFIG */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_DIRECTION */
    0x0000FFFF,  /*  PIB_GPIF_CTRL_BUS_DEFAULT */
    0x00000007,  /*  PIB_GPIF_CTRL_BUS_POLARITY */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_TOGGLE */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000000,  /*  PIB_GPIF_CTRL_BUS_SELECT */
    0x00000006,  /*  PIB_GPIF_CTRL_COUNT_CONFIG */
    0x00000000,  /*  PIB_GPIF_CTRL_COUNT_RESET */
    0x0000FFFF,  /*  PIB_GPIF_CTRL_COUNT_LIMIT */
    0x0000010A,  /*  PIB_GPIF_ADDR_COUNT_CONFIG */
    0x00000000,  /*  PIB_GPIF_ADDR_COUNT_RESET */
    0x0000FFFF,  /*  PIB_GPIF_ADDR_COUNT_LIMIT */
    0x00000000,  /*  PIB_GPIF_STATE_COUNT_CONFIG */
    0x0000FFFF,  /*  PIB_GPIF_STATE_COUNT_LIMIT */
    0x0000010A,  /*  PIB_GPIF_DATA_COUNT_CONFIG */
    0x00000000,  /*  PIB_GPIF_DATA_COUNT_RESET */
    0x0000FFFF,  /*  PIB_GPIF_DATA_COUNT_LIMIT */
    0x00000000,  /*  PIB_GPIF_CTRL_COMP_VALUE */
    0x00000000,  /*  PIB_GPIF_CTRL_COMP_MASK */
    0x00000000,  /*  PIB_GPIF_DATA_COMP_VALUE */
    0x00000000,  /*  PIB_GPIF_DATA_COMP_MASK */
    0x00000000,  /*  PIB_GPIF_ADDR_COMP_VALUE */
    0x00000001,  /*  PIB_GPIF_ADDR_COMP_MASK */
    0x00000000,  /*  PIB_GPIF_DATA_CTRL */
    0x00000000,  /*  PIB_GPIF_INGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_INGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_INGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_INGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_EGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_EGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_EGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_EGRESS_DATA */
    0x00000000,  /*  PIB_GPIF_INGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_INGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_INGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_INGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_EGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_EGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_EGRESS_ADDRESS */
    0x00000000,  /*  PIB_GPIF_EGRESS_ADDRESS */
    0x00010400,  /*  PIB_GPIF_THREAD_CONFIG */
    0x00010400,  /*  PIB_GPIF_THREAD_CONFIG */
    0x00010400,  /*  PIB_GPIF_THREAD_CONFIG */
    0x00010400,  /*  PIB_GPIF_THREAD_CONFIG */
    0x00000000,  /*  PIB_GPIF_LAMBDA_STAT */
    0x00000000,  /*  PIB_GPIF_ALPHA_STAT */
    0x00000000,  /*  PIB_GPIF_BETA_STAT */
    0x00080000,  /*  PIB_GPIF_WAVEFORM_CTRL_STAT */
    0x00000000,  /*  PIB_GPIF_WAVEFORM_SWITCH */
    0x00000000,  /*  PIB_GPIF_WAVEFORM_SWITCH_TIMEOUT */
    0x00000000,  /*  PIB_GPIF_CRC_CONFIG */
    0x00000000,  /*  PIB_GPIF_CRC_DATA */
    0xFFFFFFF1  /*  PIB_GPIF_BETA_DEASSERT */
};

/* Summary
   This structure holds configuration inputs for the GPIF II. 
 */
const CyU3PGpifConfig_t Async_Sram_CyFxGpifConfig  = {
    (uint16_t)(sizeof(Async_Sram_CyFxGpifWavedataPosition)/sizeof(uint8_t)),
    Async_Sram_CyFxGpifWavedata,
    Async_Sram_CyFxGpifWavedataPosition,
    (uint16_t)(sizeof(Async_Sram_CyFxGpifTransition)/sizeof(uint16_t)),
    Async_Sram_CyFxGpifTransition,
    (uint16_t)(sizeof(Async_Sram_CyFxGpifRegValue)/sizeof(uint32_t)),
    Async_Sram_CyFxGpifRegValue
};

#endif   /* _INCLUDED_CYFXGPIF2CONFIG_ */
